const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="CEP2";let S=JSON.parse(localStorage.getItem(KEY)||'{"results":[],"level":1,"journal":""}');
const skills={team:"Q1 · Travail d'équipe",partner:"Q2 · Partenariat",institution:"Q3 · Projet institutionnel",quality:"Q4 · Qualité",email:"Q5 · Écrit professionnel"};
const ex=[
[1,"team","QCM","Quels acteurs appartiennent à l’équipe interne du relais familial ?",["PMI et Mission locale","Cheffe de service, éducateurs référents, ME/TISF, psychologue, ASS","Crèche uniquement"],1,"La correction distingue équipe interne et partenaires."],
[1,"partner","Vrai/Faux","Pour Q2, citer les partenaires suffit.",["Vrai","Faux"],1,"Il faut sélectionner et argumenter : rôle, objectif, coopération et continuité."],
[1,"institution","QCM","Quelles orientations sont explicitement données ?",["Parentalité, autonomie, accès aux droits, prévention des ruptures","Sport, logement, loisirs","Uniquement l’insertion"],0,"Il faut rester sur les orientations présentes dans le cas."],
[1,"quality","QCM","Quel indice est central pour Q4 ?",["Maya veut se former","Plusieurs professionnels contactent séparément la crèche et elle demande un interlocuteur identifié","La crèche existe"],1,"C’est le dysfonctionnement directement exploitable pour une amélioration."],
[1,"email","QCM","Que doit contenir le mail Q5 ?",["Toute l’histoire familiale","Objet, destinataire, contexte utile, demande claire, infos nécessaires, signature","Une dissertation"],1,"Le support attendu est un mail de coordination professionnel et concis."],
[2,"team","Analyse","Maya sollicite peu l’équipe quand les démarches se cumulent. Que fais-tu ?",["Je décide pour elle.","Je transmets l’observation, la confronte aux autres informations et participe à l’ajustement collectif.","Je garde l’info."],1,"Réflexe : observer → transmettre → confronter → analyser → ajuster."],
[2,"partner","Analyse","Pourquoi la crèche est-elle prioritaire ?",["Elle remplace l’équipe.","La garde de Lina conditionne la formation et la crèche demande un interlocuteur identifié.","Elle connaît toute l’histoire familiale."],1,"Le partenariat doit servir l’objectif concret du parcours."],
[2,"institution","QCM","Soutenir l’autonomie signifie…",["Faire les démarches à sa place.","Soutenir l’anticipation et la mobilisation des ressources sans se substituer.","La laisser seule."],1,"La correction insiste sur le soutien sans substitution."],
[2,"quality","QCM","Quel raisonnement correspond à Q4 ?",["Je repère → j’explique le risque → je propose → j’évalue.","Je critique → je sanctionne.","Je communique mieux."],0,"Une action qualité doit être concrète et évaluable."],
[2,"email","QCM","Quelle information ne doit pas être transmise ?",["Projet de formation utile","Coordination nécessaire","Histoire familiale sans lien, que Maya ne veut pas partager"],2,"Partager seulement les informations nécessaires respecte le choix de Maya."],
[3,"team","Cas","La réunion d’équipe a été annulée. Quel raisonnement ?",["Élément du cas → analyse → positionnement ME → proposition → finalité","Réciter le cours","Décider immédiatement"],0,"C’est la formule centrale du sujet blanc."],
[3,"partner","Cas","Comment éviter les contacts multiples avec la crèche ?",["Chacun appelle séparément.","Mise en commun interne, interlocuteur identifié, objectif/rôles clarifiés, traçabilité et retour équipe.","La crèche décide de tout."],1,"La coordination interne conditionne la qualité du partenariat."],
[3,"institution","Cas","Quelle articulation est correcte ?",["Autonomie + prévention des ruptures : travailler l’anticipation et coordonner crèche/formation.","Inventer une nouvelle orientation.","Modifier le projet du service."],0,"Relier l’orientation institutionnelle à une action concrète dans la situation."],
[3,"quality","Cas","Quelle action qualité est réaliste ?",["Créer seul une procédure obligatoire.","Proposer un interlocuteur identifié, tracer les échanges puis évaluer l’effet.","Ne rien changer."],1,"Je repère → risque → proposition → évaluation."],
[3,"email","Cas","Quel est l’objectif du mail ?",["Raconter toute la situation.","Proposer un temps de coordination pour l’admission de Lina et demander les disponibilités.","Demander à la crèche de tout gérer."],1,"Le mail est un outil de coordination, pas un rapport."],
[4,"team","Piège correcteur","« Je travaille en équipe avec la psychologue, l’ASS et l’éducateur » est insuffisant car…",["Le ME ne travaille pas avec eux.","Ta contribution personnelle n’est pas démontrée.","Il faut citer dix personnes."],1,"Il faut montrer ce que TU observes, transmets, analyses et proposes."],
[4,"partner","Piège correcteur","« Je contacte tous les partenaires » pose quel problème ?",["Aucun.","Pas de sélection/argumentation et risque de contacts non coordonnés.","Les partenaires sont interdits."],1,"Choisir les partenaires utiles et coordonner les contacts."],
[4,"institution","Piège correcteur","Projet du service et projet de Maya :",["C’est identique.","Le service donne des orientations ; l’accompagnement les traduit dans sa situation.","Le projet de Maya modifie le service."],1,"Ne pas confondre les deux niveaux."],
[4,"quality","Piège correcteur","« Il faut mieux communiquer » suffit-il ?",["Oui.","Non : risque + action concrète + évaluation sont nécessaires.","Oui si répété."],1,"La correction attend une proposition opérationnelle."],
[4,"email","Piège correcteur","Pourquoi un mail racontant l’histoire familiale peut pénaliser ?",["Parce qu’un mail ne peut parler d’un enfant.","Informations inutiles et choix de Maya non respecté.","Parce qu’un mail doit faire 2 lignes."],1,"Confidentialité et informations strictement nécessaires."],
];
function save(){localStorage.setItem(KEY,JSON.stringify(S));render()}
function go(id){$$(".page").forEach(p=>p.classList.toggle("active",p.id===id));if(id==="training")drawEx();if(id==="exam")drawExam();if(id==="dashboard"||id==="progress")render();scrollTo(0,0)}
$$("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));
function pct(k){let a=S.results.filter(x=>x.skill===k);return a.length?Math.round(a.reduce((s,x)=>s+x.ok,0)/a.length*100):0}
function render(){let a=S.results,avg=a.length?Math.round(a.reduce((s,x)=>s+x.ok,0)/a.length*100):0;$("#avg").textContent=avg+"%";$("#done").textContent=a.length;let ps=Object.keys(skills).map(pct);$("#solid").textContent=ps.filter(x=>x>=80).length;$("#weak").textContent=ps.filter(x=>x<60).length;let html=Object.entries(skills).map(([k,v])=>`<div class="barline"><div><span>${v}</span><b>${pct(k)}%</b></div><div class="bar"><i style="width:${pct(k)}%"></i></div></div>`).join("");$("#bars").innerHTML=html;$("#progressbars").innerHTML=html;let w=Object.keys(skills).sort((a,b)=>pct(a)-pct(b))[0];$("#next").innerHTML=a.length?`Priorité : <b>${skills[w]}</b> (${pct(w)}%). Fais un exercice ciblé, puis remonte d’un niveau quand tu es régulière.`:"Commence par le niveau 1 : il sert de diagnostic.";let errs=a.filter(x=>!x.ok).slice(-8).reverse();$("#errors").innerHTML=errs.length?errs.map(x=>`<div class="feedback"><b>${skills[x.skill]}</b><br>${x.q}<br><small>${x.why}</small></div>`).join(""):"Aucune erreur enregistrée pour l’instant. 🎉";$("#journal").value=S.journal||""}
function smart(){let ps=Object.keys(skills).map(pct),avg=ps.reduce((a,b)=>a+b,0)/5;S.level=avg>=90?5:avg>=75?4:avg>=55?3:avg>=30?2:1}
function drawEx(){let l=S.level||1,f=$("#filter").value,p=ex.filter(e=>e[0]===l&&(f==="all"||e[1]===f));if(!p.length)p=ex.filter(e=>e[0]===l);let e=p[Math.floor(Math.random()*p.length)];$("#exercise").innerHTML=`<article class="exercise"><span class="tag">NIVEAU ${e[0]} · ${e[2]}</span><h3>${e[3]}</h3><div class="options">${e[4].map((o,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)} · ${o}</button>`).join("")}</div><div id="fb"></div></article>`;$$(".option").forEach(b=>b.onclick=()=>{let ok=+b.dataset.i===e[5];$$(".option").forEach(x=>x.disabled=true);S.results.push({skill:e[1],ok:ok?1:0,q:e[3],why:e[6]});if(ok&&e[0]===S.level&&S.level<5&&pct(e[1])>=75)S.level++;save();$("#fb").innerHTML=`<div class="feedback"><b>${ok?"✅ Bonne mobilisation !":"❌ À retravailler."}</b><p>${e[6]}</p><button class="${ok?"secondary":"primary"}" id="next">Continuer →</button></div>`;$("#next").onclick=drawEx})}
function levels(){for(let i=1;i<=5;i++){let b=document.createElement("button");b.className="level"+(i===S.level?" active":"");b.innerHTML=i+"<br><small>"+["Je connais","Je comprends","Je mobilise","J’analyse","Certification"][i-1]+"</small>";b.onclick=()=>{S.level=i;levels();drawEx()};$("#levels").appendChild(b)}}
$("#filter").onchange=drawEx;$("#smart").onclick=()=>{smart();levels();drawEx()};$("#save").onclick=()=>{S.journal=$("#journal").value;save();$("#saved").textContent="✓ Enregistré";setTimeout(()=>$("#saved").textContent="",1500)};
const memo=[["🧩 Formule centrale","Élément précis du cas → analyse → positionnement ME/TISF → action/proposition → finalité."],["👥 Q1 · Équipe","Acteur → mission → contribution. Pour toi : observer → transmettre → confronter → participer à l’analyse → ajuster."],["🤝 Q2 · Partenariat","Partenaire → pourquoi lui ? → objectif commun → rôles → infos nécessaires → coordination → traçabilité → continuité."],["🏛️ Q3 · Institution","Dans le sujet : parentalité, autonomie, accès aux droits, prévention des ruptures. Relier orientation et action concrète."],["🛠️ Q4 · Qualité","JE REPÈRE → J’EXPLIQUE LE RISQUE → JE PROPOSE → J’ÉVALUE."],["✉️ Q5 · Mail","Objet + destinataire + contexte utile + demande concrète + informations nécessaires + disponibilités + formule + signature."],["🔐 Confidentialité","Question réflexe : « Est-ce nécessaire à la coordination ? » Ne pas transmettre l’histoire familiale sans lien que Maya refuse de partager."],["⚠️ Pièges","Cours récité, liste de partenaires, agir seul, décider à la place, inventer, confondre équipe/partenariat, trop d’informations, rapport à la place du mail."],["🧠 Positionnement","Privilégier : observer, repérer, transmettre, participer, proposer, mobiliser, contribuer, évaluer. Ne pas s’attribuer une décision hors de son champ."]];
$("#memos").innerHTML=`<div class="memo-grid">${memo.map(x=>`<article class="memo"><h3>${x[0]}</h3><div class="formula">${x[1]}</div></article>`).join("")}</div>`;
function drawExam(){$("#exambox").innerHTML=`${["Q1 · Travail d’équipe — 4 points","Q2 · Travail partenarial — 4 points","Q3 · Projet du service — 3 points","Q4 · Amélioration qualité — 3 points","Q5 · Mail professionnel — 4 points"].map((t,i)=>`<div class="examq"><b>${t}</b><p>${["Identifie les acteurs internes utiles et explique ta contribution personnelle.","Explique comment mobiliser les partenaires pour soutenir le projet et assurer la continuité.","Relie l’intervention aux orientations du relais familial.","Repère une amélioration réaliste : risque, proposition, évaluation.","Rédige un mail à la crèche pour proposer un temps de coordination concernant Lina."][i]}</p><textarea placeholder="Ta réponse…"></textarea></div>`).join("")}<div class="examq"><b>Qualité de copie — 2 points</b><div class="check">${["J’ai répondu à tout.","J’ai utilisé des éléments du cas.","J’ai distingué mon rôle.","Mes propositions sont réalistes.","J’ai respecté confidentialité et informations nécessaires.","J’ai argumenté.","Mon écrit est clair et professionnel."].map(x=>`<label><input type="checkbox"> ${x}</label>`).join("")}</div></div><button class="primary" id="finish">Terminer l’auto-évaluation</button><div id="examres"></div>`;$("#finish").onclick=()=>{let n=$$("#exambox input").filter(x=>x.checked).length;$("#examres").innerHTML=`<div class="feedback"><b>Auto-évaluation : ${Math.round(n/7*20)}/20</b><p>Indicateur d’entraînement uniquement. Reprends les critères non cochés et compare tes réponses à la logique attendue.</p></div>`}}
$("#newExam").onclick=drawExam;levels();render();drawEx();drawExam();